services:
  - type: web
    plan: free
    name: ManyuvGaming
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn ManyuvGaming.asgi:application -k uvicorn.workers.UvicornWorker'

